sonar.projectKey=PaddleWrapper
sonar.projectName=PaddleWrapper
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/*.Tests/**,**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=./coverage/**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/*.trx

sonar.coverage.exclusions=**/*.Tests/**,**/Program.cs

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S1118
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.Extensions.cs 